apiVersion: v1
kind: Service
metadata:
  name: {{ include "ncw.fullname" . }}
  labels:
    {{- include "ncw.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "ncw.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
